### ISSUE TITLE
grep !/^_/

### ISSUE THREAD

**Issue by tobyink** [haarg/Types-QuacksLike#1]
Maybe a good idea to exclude underscore-prefixed method names?

**Comment by haarg** [comment]
That does seem like a reasonable idea.

I'm not certain yet if I'm actually going to release this module.  It was an idea I had, so I decided to throw together an implementation.

**Comment by tobyink** [comment]
An alternative would be a utility module that exports a `methods_of` function:

    isa => HasMethods[ methods_of "HTTP::Tiny" ]

Then people could manually grep the list:

    isa => HasMethods[ grep { !/^_/ } methods_of "HTTP::Tiny" ]

`methods_of` could also be useful for `handles`.

**Comment by haarg** [comment]
For now I'm filtering out underscore methods. I'll consider a separate module or dist that just has a `methods_of` later.
